const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('island', {
  getState: () => ipcRenderer.invoke('island:state'),
  onUpdate: (cb) => ipcRenderer.on('island:update', (_e, { key, value }) => cb(key, value)),
  onHover: (cb) => ipcRenderer.on('island:hover', (_e, inside) => cb(inside)),
  reportRect: (r) => ipcRenderer.send('island:rect', r),
  onToggle: (cb) => ipcRenderer.on('island:toggle', () => cb()),
  onAnswer: (cb) => ipcRenderer.on('island:answer', () => cb()),
  onEscape: (cb) => ipcRenderer.on('island:escape', () => cb()),
  launcherOpen: (open) => ipcRenderer.send('island:launcher-open', Boolean(open)),
  media: (cmd) => ipcRenderer.send('island:media', cmd),
  open: (url) => ipcRenderer.send('island:open', url),
  openConfig: () => ipcRenderer.send('island:open-config'),
  setAccent: (hex) => ipcRenderer.send('island:accent', hex),
  setArtColor: (on) => ipcRenderer.send('island:art-color', Boolean(on)),
  installUpdate: () => ipcRenderer.send('island:install-update'),
  setFocus: (on) => ipcRenderer.send('island:focus', Boolean(on)),
  openSettings: () => ipcRenderer.send('island:open-settings'),
  launcherSearch: (input) => ipcRenderer.invoke('island:launcher-search', String(input)),
  launcherRun: (item) => ipcRenderer.send('island:launcher-run', item),
  openLauncher: () => ipcRenderer.send('island:open-launcher'),
  askCancel: () => ipcRenderer.send('island:ask-cancel'),
  share: () => ipcRenderer.invoke('island:share'),
  pin: (path) => ipcRenderer.send('island:pin', String(path)),
  unpin: (path) => ipcRenderer.send('island:unpin', String(path)),
  openApp: (path) => ipcRenderer.send('island:open-app', String(path)),
  setOrder: (kind, list) => ipcRenderer.send('island:order', kind, list),
  setNotch: (mode) => ipcRenderer.send('island:notch', String(mode)),
  flashcard: () => ipcRenderer.invoke('island:flashcard'),
  plan: (op) => ipcRenderer.send('island:plan', op),
  spotify: (op, arg) => ipcRenderer.invoke('island:spotify', op, arg),
  claudeDecide: (id, allow) => ipcRenderer.send('island:claude-decide', String(id), Boolean(allow)),
  todo: (op, arg) => ipcRenderer.send('island:todo', op, arg),
  timer: (op, arg) => ipcRenderer.send('island:timer', op, arg),
  clipboard: (op, arg) => ipcRenderer.send('island:clipboard', op, arg),
  voice: (op) => ipcRenderer.send('island:voice', op === 'cancel' ? 'cancel' : 'toggle'),
  micMute: () => ipcRenderer.send('island:mic'),
  phone: (op, arg) => ipcRenderer.send('island:phone', String(op), arg == null ? null : String(arg)),
  shelf: (op, arg) => ipcRenderer.send('island:shelf', String(op), arg),
  /** Dropped File objects -> their paths on disk. */
  shelfAdd: (files) => ipcRenderer.send('island:shelf', 'add', Array.from(files || []).map((f) => webUtils.getPathForFile(f)).filter(Boolean)),
  shelfDrag: (path) => ipcRenderer.send('island:shelf-drag', String(path)),
  shot: (op) => ipcRenderer.send('island:shot', String(op)),
  feed: (op) => ipcRenderer.send('island:feed', String(op)),
});
